# Generated by Django 4.2.4 on 2023-08-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=23)),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('number_of_tickets', models.IntegerField(null=True)),
                ('slug', models.SlugField(null=True)),
                ('tickets', models.ManyToManyField(to='app.ticket')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.user')),
            ],
        ),
        migrations.AlterField(
            model_name='place',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
